### ISSUE TITLE
Is it work with HopeRF RFM95W module?

### ISSUE THREAD

**Issue by aimanhakimzahari** [davedoesdev/node-lora-comms#4]
I tried to run the example.js file on Raspberry Pi 3 Model B+ with HopeRF RFM95W module but encountered an error.

```
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: failed
Emitted 'error' event on lora_comms instance at:
    at /home/pi/lora/node_modules/lora-comms/lib/lora-comms.js:195:22
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

```
Any help would be greatly appreciated.

**Comment by davedoesdev** [comment]
Hi @aimanhakimzahari 
I'm afraid it probably doesn't. This library is ultimately based on https://github.com/Lora-net/packet_forwarder which only works for gateway devices. I think the RFM95W is a device modem (e.g. for Arduino), right?

**Comment by aimanhakimzahari** [comment]
Yes, I agree with you @davedoesdev. RFM95W is just a simple transceiver module for lorawan nodes like Arduino board. Thank you for clarifying my question. I just found a similar issue about this matter here: https://github.com/Lora-net/packet_forwarder/issues/118.
